# Site settings
title: Sahil's Travel Diary
description: Fun stories about all the travels I do
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
